name: generate animation

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: wlltn-Dev
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#f8fafc&color_dots=#e5e7eb,#d1d5db,#9ca3af,#6b7280,#374151
            dist/github-contribution-grid-snake-dark.svg?color_snake=#f8fafc&color_dots=#0f172a,#1e293b,#334155,#64748b,#f8fafc

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
